require 'rake'
require 'rake/extensiontask'
require 'rake/testtask'
require 'rspec/core/rake_task'
require 'bundler/gem_tasks'
require 'fileutils'
require "ndtypes/version.rb"

gemspec = eval(IO.read("ndtypes.gemspec"))

ext_name = "ruby_ndtypes"
Rake::ExtensionTask.new(ext_name, gemspec) do |ext|
  ext.ext_dir = "ext/#{ext_name}"
  ext.source_pattern = "**/*.{c, h}"
end

def run *cmd
  sh(cmd.join(" "))
end

BASEDIR = Pathname( __FILE__ ).dirname.relative_path_from( Pathname.pwd )
SPECDIR = BASEDIR + 'spec'

VALGRIND_OPTIONS = [
    "--tool=memcheck",
    #"--leak-check=yes",
    "--num-callers=15",
    #"--error-limit=no",
    "--partial-loads-ok=yes",
    "--undef-value-errors=no" #,
    #"--dsymutil=yes"
]

CALLGRIND_OPTIONS = [
    "--tool=callgrind",
    "--dump-instr=yes",
    "--simulate-cache=yes",
    "--collect-jumps=yes"
]

VALGRIND_MEMORYFILL_OPTIONS = [
    "--freelist-vol=100000000",
    "--malloc-fill=6D",
    "--free-fill=66 ",
]

GDB_OPTIONS = []

namespace :spec do
  # partial-loads-ok and undef-value-errors necessary to ignore
  # spurious (and eminently ignorable) warnings from the ruby
  # interpreter

  RSPEC_CMD = [ 'ruby', '-S', 'rspec', '-Ilib:ext', SPECDIR.to_s ]

  desc "Run specs under GDB."
  task :gdb => [ :compile ] do |task|
          cmd = [ 'gdb' ] + GDB_OPTIONS
    cmd += [ '--args' ]
    cmd += RSPEC_CMD
    run( *cmd )
  end

  desc "Run specs under cgdb."
  task :cgdb => [ :compile ] do |task|
    cmd = [ 'cgdb' ] + GDB_OPTIONS
    cmd += [ '--args' ]
    cmd += RSPEC_CMD
    run( *cmd )
  end

  desc "Run specs under Valgrind."
  task :valgrind => [ :compile ] do |task|
    cmd = [ 'valgrind' ] + VALGRIND_OPTIONS
    cmd += RSPEC_CMD
    run( *cmd )
  end

  desc "Run specs under Callgrind."
  task :callgrind => [ :compile ] do |task|
    cmd = [ 'valgrind' ] + CALLGRIND_OPTIONS
    cmd += RSPEC_CMD
    run( *cmd )
  end
end

LEAKCHECK_CMD = [ 'ruby', '-Ilib:ext', "#{SPECDIR}/leakcheck.rb" ]

desc "Run leakcheck script."
task :leakcheck => [ :compile ] do |task|
  cmd = [ 'valgrind' ] + VALGRIND_OPTIONS
  cmd += LEAKCHECK_CMD
  run( *cmd )
end


Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/**/test_*.rb']
end

task :clobber do |task|
  [
    "ext/#{ext_name}/include",
    "ext/#{ext_name}/share",
    "ext/#{ext_name}/lib",
  ].each do |f|
    puts "deleting folder #{f}..."
    FileUtils.rm_rf(f)
  end

  Dir.chdir("ext/#{ext_name}/ndtypes/libndtypes/") do
    system("make clean")
  end
end

task :develop do |task|
  ext_ndtypes = "ext/ruby_ndtypes/ndtypes"
  puts "deleting previously created #{ext_ndtypes} directory..."
  FileUtils.rm_rf(ext_ndtypes)
  Dir.mkdir(ext_ndtypes)

  puts "cloning ndtypes repo into ext/ folder..."
  system("git clone https://github.com/plures/ndtypes #{ext_ndtypes}")

  Dir.chdir(ext_ndtypes) do
    system("git checkout #{NDTypes::COMMIT}")
  end

  puts "building gem with rake build..."
  system("rake build")
end
